import argparse
import os
import shlex
import subprocess
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', required=True)
    parser.add_argument('--input_dir', required=True)
    parser.add_argument('--output_dir', required=True)
    parser.add_argument('--ckpt', required=True)
    parser.add_argument('--env_cmd_key', required=True)
    return parser.parse_args()


def _normalize_output(output_dir: Path):
    output_image = output_dir / 'output.png'
    if output_image.exists():
        return
    candidates = []
    for suffix in ('*.png', '*.jpg', '*.jpeg', '*.bmp', '*.tiff'):
        candidates.extend(output_dir.rglob(suffix))
    if not candidates:
        raise RuntimeError('No output image generated by external desnow command')
    candidates[0].replace(output_image)


def main():
    args = parse_args()
    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    cmd_template = os.getenv(args.env_cmd_key, '').strip()
    if not cmd_template:
        raise RuntimeError(
            f"Missing environment variable {args.env_cmd_key}. "
            f"Please set a command template with placeholders {{input_dir}} {{output_dir}} {{ckpt}}."
        )

    cmd = cmd_template.format(
        input_dir=str(input_dir),
        output_dir=str(output_dir),
        ckpt=str(Path(args.ckpt).resolve()),
        model_name=args.model_name,
    )

    subprocess.run(cmd, shell=True, check=True)
    _normalize_output(output_dir)


if __name__ == '__main__':
    main()
